### ISSUE TITLE
Redis does not bind to all interfaces on Ubuntu machines

### ISSUE THREAD

**Issue by tculp** [cmacrae/ansible-sensu#104]
In tasks/Debian/redis.yml, the following block appears:

  - name: Ensure redis binds to accessible IP
    lineinfile:
      dest: /etc/redis/redis.conf
      regexp: '^bind'
      line: 'bind 0.0.0.0'
    notify: restart redis service

This is not present in tasks/Ubuntu/redis.yml, and as such redis does not bind to all interfaces on Ubuntu machines

**Comment by jaredledvina** [comment]
PR Merged! Thank you!
