### ISSUE TITLE
Role does not deploy client definitions / standalone checks

### ISSUE THREAD

**Issue by tculp** [cmacrae/ansible-sensu#111]
Server-defined checks, definitions are deployed using the static data store, but the same is not true for client-defined (standalone) checks, other than the custom client config

**Comment by jaredledvina** [comment]
Hey @tculp,

Thanks so much for the PR and sorry for the delay here. I'm going to try to test out your change over the holidays just to make sure it's solid. Quick look looks great to me!

**Comment by tculp** [comment]
@jaredledvina Thanks! I hope you find it satisfactory, and please let me know if you find any issues

**Comment by jaredledvina** [comment]
The PR is finally merged, I'm very sorry about the delay there. With the basic integration tests running now, the process should be much faster, let me know if you have any other issues and thanks!
