### ISSUE TITLE
Fixup Ansible ReadTheDocs builds

### ISSUE THREAD

**Issue by jaredledvina** [cmacrae/ansible-sensu#135]
I noticed that the [ReadTheDocs](https://ansible-sensu.readthedocs.io/) site doesn't appear to be building. https://readthedocs.org/projects/ansible-sensu/builds/ 

I think this is because of the repo move. I tried to see what I could do but, I don't have any access to the project and it looks like only @cmacrae has access/owns it. 

@cmacrae - Any chance you could add myself and @cjchand as Admins on that project? My ReadTheDocs account is https://readthedocs.org/profiles/jaredledvina/

**Comment by jaredledvina** [comment]
Hey @cmacrae, any chance you'd be able to take a look here?

**Comment by cmacrae** [comment]
So sorry about missing this, I don't know how this slipped past - I never saw a notification! 🙏   
As you can see, I've commented on the above referenced ticket.  

If there are things like this in the future @jaredledvina - and I don't reply in a reasonable amount of time, please feel free to shoot me an e-mail directly

**Comment by cmacrae** [comment]
@jaredledvina There ya go - permission granted 🙂 I wasn't able to add @cjchand as a maintainer on the docs, however; as apparently a user with that name on RTD doesn't exist

**Comment by cjchand** [comment]
Sorry about that, @cmacrae. I’m on RTD now as cjchand.

**Comment by cmacrae** [comment]
No problem @cjchand! You're now a maintainer too 👍

**Comment by cmacrae** [comment]
Feel free to reopen this if you guys need anything for it

**Comment by jaredledvina** [comment]
Hey @cmacrae,

Awesome, thanks so much! I updated the build URL and we've now got docs builds successfully going https://readthedocs.org/projects/ansible-sensu/builds/ 
🎉
