### ISSUE TITLE
Failed to install sensu on Redhat

### ISSUE THREAD

**Issue by mohanrao** [cmacrae/ansible-sensu#148]
Hi , 

I am using the latest ansible with my playbook having the below code
```
- hosts: sensu-servers
    roles:
      - role: cmacrae.sensu

**It is failing at the step of  Deploy the Sensu client SSL cert/Key**



[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion.
This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [sensu-servers] ***********************************************************

TASK [Gathering Facts] *********************************************************
ok: [sensu-server]

TASK [cmacrae.sensu : include_vars] ********************************************
ok: [sensu-server]

TASK [cmacrae.sensu : include] *************************************************
included: /home/mohan/.ansible/roles/cmacrae.sensu/tasks/RedHat/main.yml for cd-a                                                                                                                     rch-072

TASK [cmacrae.sensu : include_vars] ********************************************
ok: [sensu-server]

TASK [cmacrae.sensu : Set sensu_pkg_version RedHat override] *******************
ok: [sensu-server]

TASK [cmacrae.sensu : Ensure the Sensu Core Yum repo is present] ***************
ok: [sensu-server]

TASK [cmacrae.sensu : Ensure that credential is supplied if installing Sensu Ent                                                                                                                     erprise] ***
skipping: [sensu-server]

TASK [cmacrae.sensu : Ensure the Sensu Enterprise repo is present] *************
skipping: [sensu-server]

TASK [cmacrae.sensu : Ensure the Sensu Enterprise Dashboard repo is present] ***
skipping: [sensu-server]

TASK [cmacrae.sensu : Ensure Sensu is installed] *******************************
ok: [sensu-server]

TASK [cmacrae.sensu : Ensure Sensu Enterprise is installed] ********************
skipping: [sensu-server]

TASK [cmacrae.sensu : include] *************************************************
skipping: [sensu-server]

TASK [cmacrae.sensu : include] *************************************************
included: /home/mohan/.ansible/roles/cmacrae.sensu/tasks/ssl.yml for sensu-server

TASK [cmacrae.sensu : include_vars] ********************************************
ok: [sensu-server]

TASK [cmacrae.sensu : Ensure Sensu SSL directory exists] ***********************
ok: [sensu-server]

TASK [cmacrae.sensu : include] *************************************************
included: /home/mohan/.ansible/roles/cmacrae.sensu/tasks/ssl_generate.yml for cd-                                                                                                                     arch-072

TASK [cmacrae.sensu : include_vars] ********************************************
ok: [sensu-server]

TASK [cmacrae.sensu : Ensure SSL generation directory exists] ******************
skipping: [sensu-server]

TASK [cmacrae.sensu : Untar the ssl_certs tarball from sensuapp.org] ***********
skipping: [sensu-server]

TASK [cmacrae.sensu : Generate SSL certs] **************************************
skipping: [sensu-server]

TASK [cmacrae.sensu : Stash the Sensu SSL certs/keys] **************************
skipping: [sensu-server] => (item=sensu_ca/cacert.pem)
skipping: [sensu-server] => (item=server/cert.pem)
skipping: [sensu-server] => (item=server/key.pem)
skipping: [sensu-server] => (item=client/cert.pem)
skipping: [sensu-server] => (item=client/key.pem)

TASK [cmacrae.sensu : Deploy the Sensu client SSL cert/key] ********************
fatal: [sensu-server]: FAILED! => {"msg": "{{ sensu_ssl_tool_base_path }}/client/cert.pem: {{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}{{sensu_master_config_path }}/ssl_generation/sensu_ssl_tool: {{hostvars[groups['sensu_masters'][0]]['sensu_config_path'] | default('/etc/sensu') }}: 'dict object' has no attribute 'sensu_masters'"}
        to retry, use: --limit @/home/mohan/sensu/site.retry

PLAY RECAP *********************************************************************
sensu-server                : ok=12   changed=0    unreachable=0    failed=1

[mohan@ansible sensu]$ ansible-playbook --version
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mohan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

**Comment by jaredledvina** [comment]
Hey @mohanrao,

Taking a quick look at your output:
```
fatal: [sensu-server]: FAILED! => {"msg": "{{ sensu_ssl_tool_base_path }}/client/cert.pem: {{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}{{sensu_master_config_path }}/ssl_generation/sensu_ssl_tool: {{hostvars[groups['sensu_masters'][0]]['sensu_config_path'] | default('/etc/sensu') }}: 'dict object' has no attribute 'sensu_masters'"}
```

It looks like you don't have a hostgroup called `sensu_masters`. It's not required (especially if you are only running the entire stack on one node). https://ansible-sensu.readthedocs.io/en/latest/single_master/ documents some alternatives. Can you give the options outlined in that doc a shot and let me know if anything doesn't make sense?

**Comment by mohanrao** [comment]
@jaredledvina Thanks. It worked!

**Comment by ghost** [comment]
Hello,

I'm deploying a full Sensu stack with this role. I'm downloading and running it with Packer/Docker, but I'm getting this same error. Changing RabbitMQ/Redis/Sensu host to _localhost_ in a similar way the doc shows doesn't help.

I've found that two more variables could be related to this problem as they mention the same variable:
*sensu_master_config_path
*sensu_ssl_tool_base_path

But can't figure how to success.

My playbook:
``` 
---
  - name: Sensu Install
    hosts: localhost
    become: true
    roles:
    - role: sensu.sensu
      sensu_master: true
      rabbitmq_host: localhost
      redis_host: localhost
      sensu_api_host: localhost
      sensu_include_dashboard: true
      sensu_deploy_rabbitmq_server: true
      sensu_deploy_redis_server: true
      rabbitmq_sensu_user_name: sensu
      rabbitmq_sensu_password: change_me
      redis_password: change_me
      sensu_api_user_name: admin
      sensu_api_password: change_me
```

**Comment by cjchand** [comment]
@beeva-diegombeltran: Can you provide a redacted the output from the run of your playbook? Sounds like you're looking to deploy an all-in-one (Rabbit, Redis, Sensu, Uchiwa all on the same box), but let me know if that's not the case.

**Comment by tolusonaike** [comment]
> Hello,
> 
> I'm deploying a full Sensu stack with this role. I'm downloading and running it with Packer/Docker, but I'm getting this same error. Changing RabbitMQ/Redis/Sensu host to _localhost_ in a similar way the doc shows doesn't help.
> 
> I've found that two more variables could be related to this problem as they mention the same variable:
> *sensu_master_config_path
> *sensu_ssl_tool_base_path
> 
> But can't figure how to success.


This was confusing to me as well. You are getting that error because those 2 variables require `groups['sensu_masters']` but the Doc says it is not a required group. I tried setting `sensu_ssl_gen_certs` and `sensu_ssl_manage_certs` to false but the ruby service will not run because it is looking for the certs.

You can either override those variables with your own groups or add a 'sensu_masters' group with the same host to your inventory file

**Comment by ghost** [comment]
Hi, I don't know why GitHub isn't notifying me... anyway:

Yes, I'm trying to deploy all in the same box. I managed to workaround it by running the playbook with an inventory file (sensu_masters group), but it's not a good way, because I'm trying to launch the role from a GitLab CI pipeline, using Ansible dynamic inventories.

**Comment by beeva-diegombeltran** [comment]
BTW, here is the output:

`TASK [sensu.sensu : Deploy the Sensu client SSL cert/key] **********************
fatal: [ip-10-0-103-168.eu-central-1.compute.internal]: FAILED! => {"msg": "'dict object' has no attribute 'sensu_masters'"}
	to retry, use: --limit @/builds/OrangeX/System/Provisioning/serviceassurance-sensu-provision/sensu.retry`

**Comment by ghost** [comment]
BTW, here is the output:

> TASK [sensu.sensu : Deploy the Sensu client SSL cert/key] **********************
> fatal: [Machine_DNS_Name]: FAILED! => {"msg": "'dict object' has no attribute 'sensu_masters'"}
> 	to retry, use: --limit @[XXXXXXXXXXXXXXXX]/sensu.retry

**Comment by tolusonaike** [comment]
@beeva-diegombeltran  looks like you override the **sensu_ssl_tool_base_path** (that requires `{{ groups['sensu_masters'][0] }}`) variable with your dynamic host/group var. If AWS, then tags from ec2.py? If you are managing ssl in other ways, you can always turn off managing the certs to skip that task

**Comment by beeva-diegombeltran** [comment]
Hello,

Yes, I'm using ec2.py. I'm not managing SSL generation in a different way, and it would be right if I do it with the Sensu role. Anyway, just to try, I'm going to turn off the certs generation for now and post here the results.

**Comment by ghost** [comment]
Hello,

Yes, I'm using ec2.py. I'm not managing SSL generation in a different way, and it would be right if I do it with the Sensu role. Anyway, just to try, I'm going to turn off the certs generation for now and post here the results.

EDIT--> Looks ok with the SSL generation set to false.

**Comment by ghost** [comment]
Well, it works... but there aren't any certificates in /etc/sensu/ssl... so not working at all.
