### ISSUE TITLE
tls: oversized record received with length 20527

### ISSUE THREAD

**Issue by lukyanov** [cmacrae/ansible-sensu#15]
When I create a Sensu master I get the following message in uchiwa.log:

```
{"timestamp":"2016-04-14T13:21:55.54069187Z","level":"warn","message":"GET https://mon:4567/stashes returned: Get https://mon:4567/stashes: tls: oversized record received with length 20527"}
```

Plain curl won't also work:

```
$ curl "https://mon:4567/stashes"
curl: (35) SSL received a record that exceeded the maximum permissible length.
```

My configuration of the role:

```
sensu_include_dashboard: true
sensu_deploy_rabbitmq: true
sensu_deploy_redis: true
sensu_api_host: '{{ inventory_hostname }}'
sensu_api_ssl: 'true'
sensu_master: true
sensu_ssl_gen_certs: true
sensu_master_config_path: '{{ sensu_config_path }}'
sensu_ssl_tool_base_path: "{{ dynamic_data_store }}/{{ inventory_hostname }}{{ sensu_master_config_path }}/ssl_generation/sensu_ssl_tool"

rabbitmq_server: true
rabbitmq_host: localhost

redis_server: true
redis_host: localhost
```

What could be the issue?

**Comment by lukyanov** [comment]
Does Sunsu support https for sensu-api? Perhaps it doesn't... That's why I'm getting this.

**Comment by jaredledvina** [comment]
Hey @lukyanov, sorry that you didn't get a reply to this sooner, were you ever able to sort this out? 
Looking at the Sensu API docs, https://sensuapp.org/docs/latest/api/configuration.html it doesn't seem that the Sensu API currently supports HTTPS.

**Comment by jaredledvina** [comment]
I'm going to close this out as the Sensu API does not currently support native SSL. Feel free to open an FR on the https://github.com/sensu/sensu/ project for that. Let me know if you run into any other issues!
