### ISSUE TITLE
Prefix for all variables

### ISSUE THREAD

**Issue by lukyanov** [cmacrae/ansible-sensu#16]
Great experience overall with the role! Thank you for sharing this.

There is one thing I would suggest. It's a great practice to prefix all the variables of the role with the role name (`sensu_`). The practical reason for that is that you reduce the risk of interfering with the rest of the Ansible project you are working on.

It just happened to me. I have an independent RabbitMQ server absolutely not related to Sensu, just for some application purposes. I wanted to install a separate instance of a RabbitMQ server with your role. I spent quite some time figuring out why my own RabbitMQ server gets SSL keys and restarts while I'm provisioning my servers with your role :) Finally I realized that my server has an inventory variable `rabbitmq_server` which causes the role to do some actions for that.

**Comment by jaredledvina** [comment]
Hey @lukyanov,
Sorry again that you didn't get a follow up to this sooner! This is a totally fair ask and something I can work on putting together. If you feel like throwing in a PR as well, I'm happy to review/test it out.

**Comment by jaredledvina** [comment]
Finally closed out in https://github.com/sensu/sensu-ansible/releases/tag/5.0.0 via https://github.com/sensu/sensu-ansible/pull/206 

This was delayed for far too long but, we finally got it in.
