### ISSUE TITLE
Build/Gem install: Public key required to build Sensu 1.4.2 (and possibly later)

### ISSUE THREAD

**Issue by cjchand** [cmacrae/ansible-sensu#160]
As called out in [#1865 of the Sensu core repo](https://github.com/sensu/sensu/issues/1865), attempts to build the Sensu gem require the public key to do so. [Issue #1865 of the Sensu core repo](https://github.com/sensu/sensu/issues/1865) has a workaround, should you need it.

Specific to this Ansible role, that would only potentially affect SmartOS and OpenBSD. The role defaults to 0.29.0, so out-of-the-box people should not be impacted.

Opening this issue to:

1. Track so we can potentially implement a solution/workaround
2. Inform interested parties should they encounter the same.

**Comment by jaredledvina** [comment]
Hmmm joy, meanwhile, I had opened https://github.com/sensu/sensu-ansible/pull/157 to deprecate the dedicated pinning variable and cleanup those code paths. Maybe we should hold off though?

**Comment by jaredledvina** [comment]
Looking more closely, I think that PR is fine, for the `gem` installs we're using `sensu_gem_state` which defaults to `present`. I'll look into adding support for the `gem cert` logic and the Medium security things as well. Looking quickly, https://docs.ansible.com/ansible/latest/modules/gem_module.html#gem-module doesn't have support for that.

**Comment by jaredledvina** [comment]
I think we're safe to close this out, the affected OS's _might_ be SmartOS and OpenBSD but, we don't have a setup to cleanly verify this + those pretty barely supported, https://github.com/sensu/sensu-ansible#supported-manually-compatibility-not-always-guaranteed. 

If anyone is running this Ansible Role and hits this issue with SmartOS/OpenBSD, if willing, do please open an issue with the details and a Pull Request if you're able.
