### ISSUE TITLE
Sensu installation on amazon linux ami.

### ISSUE THREAD

**Issue by muraliedupuganti** [cmacrae/ansible-sensu#188]
I was problem install sensu on amazon linux ami. Installation completed successfully. But not able to start sensu agent. Anyone has any experience?

Regards,
Murali.

**Comment by jaredledvina** [comment]
Hi @muraliedupuganti ,

Can you please provide some information around the errors you're seeing when starting the `sensu-client` process? Usually `/var/log/sensu/sensu-client.log` is a great start.

**Comment by muraliedupuganti** [comment]
Used the script in this repository( https://github.com/sensu/sensu-build/blob/master/sensu_configs/init.d/sensu-service#L32 ). it is working fine.
