### ISSUE TITLE
installing sensu-enterprise in Amazon Linux

### ISSUE THREAD

**Issue by FrenchToast113** [cmacrae/ansible-sensu#190]
Right now, this ansible role supports sensu-enterprise installation in centos machines only. Could you expand it further so i can install the enterprise in amazon linux 2 as well?

Thank you

**Comment by jaredledvina** [comment]
Hey @y3046308,

Great idea! I currently do not use Sensu Enterprise. If you feel up to opening a PR to expand support in this role though, feel free to! I think what we might want to do as well is get a setup that includes integration w/ TravisCI to ensure it works. I think the Chef setup already does that and that we can probably do something similar.

**Comment by jaredledvina** [comment]
Hey @y3046308, Any chance you'd be willing to open a PR to support this? I don't have access to a Sensu Enterprise install setup to test against.

**Comment by jaredledvina** [comment]
Closing this out as stale, currently, we do not have licenses for Sensu Core enterprise to build out support for this. If anyone with an existing setup is willing to open a Pull Request to add this support, I'm more than happy to review it.
