### ISSUE TITLE
Wrong client subscriptions with Amazon Tags

### ISSUE THREAD

**Issue by diegombeltran** [cmacrae/ansible-sensu#198]
Sensu role writes wrong client subscriptions if using Ansible dynamic inventory script, Amazon tags, and "sensu_client_subscriptions" variable by default:

This is how it should look like:
![github1](https://user-images.githubusercontent.com/7081281/52269082-7c7fb980-293d-11e9-800b-bfcd7cd40f1b.png)
This is how it looks after running the role:
![github](https://user-images.githubusercontent.com/7081281/52269113-8dc8c600-293d-11e9-8936-d298fda5a1f1.png)

The second picture has several Amazon EC2 instance's tags which shouldn't be used (or even checked) at all.

**Comment by jaredledvina** [comment]
Hey @diegombeltran,

Thanks for the issue, I can't say I've seen this one before so, I've got some questions. 

What have you currently configured ``sensu_client_subscriptions to? 
Currently, we default that to `group_names` here: https://github.com/sensu/sensu-ansible/blob/master/defaults/main.yml#L81 which is a special Ansible variable https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html?highlight=group_names 

I know that the ec2 inventory script automatically adds hosts to those `tag_key_val` groups, so those entries make sense to me if that's the inventory your using. 
Did you manually override `sensu_client_subscriptions` to have the two entries in the first image? If so, where/how did you configure that?

**Comment by jaredledvina** [comment]
Hey @diegombeltran, Any chance you were able to review my questions above?

**Comment by jaredledvina** [comment]
Closing this out for now, feel free to re-open if you're still having issues, happy to help!
