### ISSUE TITLE
ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'Ansi

### ISSUE THREAD

**Issue by jaredledvina** [cmacrae/ansible-sensu#2]
Hi,

Not sure what I'm messing up, but I'm receiving the follow error when applying this runbook:

```
ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'Ansi
```

```

---
-
  hosts: host1
  become: yes
  roles:
    - role: ansible-sensu
```

I think it's the way ansible is trying to combine vars. I've commented out the vars being used in `roles/ansible-sensu/defaults/main.yml` from `roles/ansible-sensu/vars/Debian.yml` but hit the same issue later one. 

```
ansible --version
ansible 2.1.0 (devel d60f0c94f8) last updated 2016/03/06 15:05:35 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 0bbb7ba38d) last updated 2016/02/29 19:37:22 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 39e4040685) last updated 2016/02/29 19:37:22 (GMT -700)
  config file = <homedir>/ansible-test/ansible.cfg
  configured module search path = Default w/o overrides
```

Any help would be greatly appreciated. Thanks!

**Comment by cmacrae** [comment]
Hey @jaredledvina :wave: 

This role hasn't been tested with Ansible 2.1 - I suspect this is the problem, as I've seen this same error message when operating on other roles written for 2.0 whilst using 2.1.

Could you please try with the latest Ansible 2.0 release?

**Comment by jaredledvina** [comment]
Hey @cmacrae, 

Yep! That worked, I'll see if I can figure out what changed in 2.1 and make a pull request, thanks for the tip

**Comment by cmacrae** [comment]
@jaredledvina great! Yeah, sweet - so long as the changes suggested are backwards compatible with 2.0 releases, I'd really appreciate that :+1:
