### ISSUE TITLE
Travis and Galaxy not refreshed.

### ISSUE THREAD

**Issue by michaelpporter** [cmacrae/ansible-sensu#216]
@jaredledvina it seems that Travis and Galaxy did not refresh with the latest release.

https://galaxy.ansible.com/sensu/sensu

https://travis-ci.org/sensu/sensu-ansible/builds

**Comment by jaredledvina** [comment]
Manually kicked it! Looks like Debian timed out which probably didn't kick off Travis? Should be live now though
