### ISSUE TITLE
bintray.com/rabbitmq/{rpm,debian}/erlang is going away

### ISSUE THREAD

**Issue by michaelklishin** [cmacrae/ansible-sensu#220]
This repository uses `https://bintray.com/rabbitmq/rpm/erlang` which has stopped receiving updates in Nov 2018. That package is [going away for good early next week](https://groups.google.com/forum/#!msg/rabbitmq-users/Gu55prdJ7uM/tftnTT_ZAwAJ). 

Please switch to `https://bintray.com/rabbitmq-erlang/rpm/erlang` which provides the most recent patch releases of Erlang 21.x, 20.3.x and 19.3.x.

This is also true for `https://bintray.com/rabbitmq/debian/erlang`.

**Comment by jaredledvina** [comment]
Ooo thanks for the heads up! If you're game to make a PR, that'd be sweet. Otherwise, I'll try to find some time to get this in.

**Comment by michaelklishin** [comment]
@jaredledvina see #221. I largely have no idea what I'm doing 😅but at least it updates repository URLs.

**Comment by jaredledvina** [comment]
Oh nice, thanks! The Travis CI integration tests for sure will exercise this, let's see what happens there and I can make sure that any future changes needed get in and we can close this out.
