### ISSUE TITLE
No permissions 

### ISSUE THREAD

**Issue by blueto01h** [cmacrae/ansible-sensu#225]
I always seem to run into some permission issue using this role. 
When using the most simple playbook (the example ones from the README) it would throw insufficeint permissions to install apt-transport-https (using debian) and do other stuff like update apt-cache etc, so I would fix this using "sudo: yes", but eventually I run into different kind of permissions problems. 
What is it that I am missing here? 
I've began to fiddle with the role playbooks, but that is surely not what would be needed.

**Comment by jaredledvina** [comment]
Hi @blueto01h !

Sorry for the trouble here. This role for sure needs `become: true` / root level permissions. I've never used or tested it in an environment where it's deployed without those. You might be able to get it to work if you disable the repo management and have it become the `sensu` user but, even then, that's probably going to get messy. 

If you're able to drop the errors you're getting with `become: true` and if possible, the playbook/tasks you're using to deploy this role, I'm more than happy to help work through the errors. 

General note as well, Sensu Core (what this role supports) is being EOL'ed by the end of this year. See https://blog.sensu.io/eol-schedule-for-sensu-core-and-enterprise for deets.

**Comment by blueto01h** [comment]
thanks for the quick response!
it works then to install the needed dependecies, it will do the same as with "sudo: yes" though: stop at 
```
"TASK [sensu.sensu : Ensure the Sensu CA serial configuration]"
fatal: [agent@192.168.2.102]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1563546755.4802456-242766864414319/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1563546755.4802456-242766864414319/AnsiballZ_command.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

it seems that it stops running as root there? ive tried added "become: sensu" and "become: true" etc within task of the ssl_generate.yml playbook of the role, but it was not affected. 
then ive created a common group for the sensu user and the default ssh user and replaced {{ sensu_group_name }} with that group in ss_generate.yml, when creating the affected files in this task, then it works, but stops at the next few files.

**Comment by jaredledvina** [comment]
Hey @blueto01h ,

Interesting! Which operating system, version of Ansible, Python, and this role are you using?

**Comment by blueto01h** [comment]
Host using ansible: 
ansible 2.8.2
python 3.73 
sensu-ansible 5.3.0
Arch Linux 

Client, "sensu-master":
python 3.5.3 
Debian stretch

**Comment by jaredledvina** [comment]
Hey @blueto01h ,

Cool, thanks. Do you have Ansible's pipelining feature enabled? See https://docs.ansible.com/ansible/latest/reference_appendices/config.html?highlight=pipelining#ansible-pipelining, from reading through https://docs.ansible.com/ansible/latest/user_guide/become.html#becoming-an-unprivileged-user it seems that sometimes when there's the use of `become` to an unprivileged user (in this case the `sensu` user via https://github.com/sensu/sensu-ansible/blob/master/tasks/ssl_generate.yml#L116-L117) the `/tmp` files can be funky. 

If you're not able to use pipelining or that doesn't work, can you try setting `allow_world_readable_tmpfiles` as outlined in https://docs.ansible.com/ansible/latest/user_guide/become.html#becoming-an-unprivileged-user in your `ansible.cfg` file?

**Comment by blueto01h** [comment]
hey @jaredledvina, that seems to work, thanks ! 
however it will stop at the task for deploying the sensu client ssl certificate + key with the following message: `fatal: [vm1]: FAILED! => {"msg": "'dict object' has no attribute 'sensu_masters'"}` 
(either method)

**Comment by jaredledvina** [comment]
@blueto01h - In your Ansible host list, do you have a group named `sensu_masters`?

**Comment by blueto01h** [comment]
@jaredledvina that did the trick! i didnt realize i had to add groups there. 
thank you very much for the help :)
