### ISSUE TITLE
Migrate to EOL repo

### ISSUE THREAD

**Issue by mho-CL** [cmacrae/ansible-sensu#228]
Hello seems like the apt repo url thats been used is not up right now, is this something to be resolved or has the url changed and just havent been updated in the repo?
sensu_apt_repo_url: "deb     https://repositories.sensuapp.org/apt

**Comment by jaredledvina** [comment]
Hi @mho-CL ,

Yes, you do appear to be correct. This Sensu Core has been End of Lived as announced in https://blog.sensu.io/eol-schedule-for-sensu-core-and-enterprise 

https://blog.sensu.io/announcing-the-sensu-archives outlines the existing archives, which until April will be available at https://eol-repositories.sensuapp.org

If you're interested in migrated to Sensu Go, https://docs.sensu.io/sensu-core/latest/migration/ outlines the process and there's a official dedicated Ansible Collection for Sensu Go that the folks at [XLab](https://www.xlab.si/?lang=en) support here https://github.com/sensu/sensu-go-ansible 

If you're willing to open a PR to update the package URL's, I'm more than happy to review it and get it merge for ya.

**Comment by mho-CL** [comment]
Ah yes. I was doing some more reading and came across Sensu Core being eol and found the url 
http://eol-repositories.sensuapp.org/apt/.

Will read up on Sensu Go.

**Comment by mho-CL** [comment]
Will make a PR as well for the package URLs

**Comment by mho-CL** [comment]
Made a PR, but if there's anything additional I can help with to get it to a "Release", let me know!
https://github.com/sensu/sensu-ansible/pull/229

**Comment by jaredledvina** [comment]
Thanks, PR looks good, the build is sad, I'll take a look at that, doesn't seem related to your change though.

**Comment by jaredledvina** [comment]
Unscrewing this via https://github.com/sensu/sensu-ansible/pull/230

**Comment by jaredledvina** [comment]
https://github.com/sensu/sensu-ansible/releases/tag/6.0.0 should be all set and synced to galaxy shortly!
