### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by 030** [cmacrae/ansible-sensu#33]
Imagine there is a bug, how to revert to a previous version?

**Comment by pporada-gl** [comment]
We fork the repository and maintain our own copy.

**Comment by kcivey** [comment]
Yes, it seems odd that this role isn't being tagged with version numbers.

**Comment by smuth4** [comment]
Sorry, I had meant to do this once the dust settled from my adoption of the repo, but dropped the ball. I've added an initial 1.0.0 version, and intend to loosely follow the [semver](http://semver.org/) standard.
