### ISSUE TITLE
Configure a check plugin?

### ISSUE THREAD

**Issue by SiKing** [cmacrae/ansible-sensu#38]
I deployed the http plugin to my client with:

```
    sensu_remote_plugins:
      - http:0.3.0
```

How do I send over a configuration file, as described in https://sensuapp.org/docs/latest/reference/checks#example-check-definition ?

**Comment by smuth4** [comment]
See https://github.com/sensu/sensu-ansible/blob/master/docs/dynamic_checks.md for instructions on how to do that.

**Comment by SiKing** [comment]
Just as a test, I placed my .json configuration in everyone of "checks", "definitions", "handlers", and "mutators". Nothing showed up in /etc/sensu/conf.d on the client.
What am I doing wrong?

**Comment by SiKing** [comment]
All of my checks look like this:

```
{
  "checks": {
    "core-service": {
      "command": "check-http.rb -u http://localhost:8080/core-service/internal/healthchecks -q 'Service is up and reachable'",
      "subscribers": [
        "development"
      ],
      "interval": 60
    }
  }
}
```

**Comment by smuth4** [comment]
They are templates, try adding `.j2` suffix

**Comment by SiKing** [comment]
I tried this:
1. Renamed all my .json to .json.j2
2. For each of the files, I added a field like: `"from": "definitions"` so that I know where the file came from. This is obviously wrong for the definition of the check, but I just want to find out where things are coming from.
3. The only thing that got pushed to the client is `plugins/check_health.json.j2`. The extra field I had added indicates this file came from "mutators".

**Comment by azconger** [comment]
I am having this issue as well.  Does this role support pushing standalone check definitions to clients, or will it only push check definitions to the master Sensu node as subscription checks?

**Comment by cjchand** [comment]
@SiKing: Apologies that it's taken this long to get back to you. We've recently had some folks take up maintenance of this repo, hence the delay. Again, apologies for that.

The short answer to your question - and @zconger's, as well - is that this role currently is focused on deploying the server-side bits. This means the only client-side checks can it will affect are any defined in sensu-server. For many instances, this is sufficient, as they use subscriptions to assign checks to hosts. Note: [As called out here](https://github.com/sensu/sensu-ansible/issues/118), we plan to split out the roles, including a `sensu-client` role which will help address what you're after.

A quick aside about subscriptions for others who may stumble upon this thread: Many folks will deploy Sensu with most (or all) checks defined server-side. These checks are then applied to clients via [subscriptions](https://sensuapp.org/docs/1.0/reference/clients.html#client-subscriptions). When using subscriptions, you will not see a config file land on the target client(s). Rather, sensu-server uses RMQ's Pub/Sub model to push a request to run that check, then all subscribers to that queue run the check and report back results.

If you want to define the checks on the clients themselves, those are called [standalone checks](https://sensuapp.org/docs/0.28/reference/checks.html#standalone-checks). These require config to be deployed on the client itself, ensuring that the `standalone` and `interval` [check attributes](https://sensuapp.org/docs/0.28/reference/checks.html#check-attributes) are set.

There are a couple of ways you can go about this. 

1. One, as you've been playing with, it to use Jinja2 templates
Another is to use the Ansible [sensu_check module](http://docs.ansible.com/ansible/latest/sensu_check_module.html)

Long-winded answer, but hope it helps. Let me know if there's any follow-up questions you have.

**Comment by jaredledvina** [comment]
Hey @SiKing / @zconger - If I'm understanding this issue correctly, I believe https://github.com/sensu/sensu-ansible/pull/112 actually solves the problem. That change will be included in the 2.0.0 release of this role which I plan to cut today/tomorrow. If you'd like to give that a shot immediately, feel free to pull the role directly from Github, 2.0.0 will be what is the current version of master. 

Interested to see if that change knocks out this issue.

**Comment by SiKing** [comment]
I am no longer working on the project where I used sensu. 2016, wow! I am no longer in the same state. :)
Sorry, I will not be able to verify this.

**Comment by azconger** [comment]
I have another project coming up soon and will be able to verify this.
Thanks for posting!

**Comment by jaredledvina** [comment]
Hey @zconger,
Any chance you were able to verify that #112 solved the issue?

**Comment by jaredledvina** [comment]
I'm going to close this out due to inactivity but, if you're still hitting issues please let me know!
