### ISSUE TITLE
ssl download error

### ISSUE THREAD

**Issue by danktec** [cmacrae/ansible-sensu#41]
Not sure why i get this 
`FAILED! => {"changed": false, "dest": "/etc/sensu/ssl_generation/sensu_ssl_tool.tar", "failed": true, "msg": "Request failed", "response": "HTTP Error 505: HTTP Version Not Supported", "state": "absent",
"status_code": 505, "url": "http://sensuapp.org/docs/0.23/files/sensu_ssl_tool.tar"}`

**Comment by danktec** [comment]
I worked around this by using executing tar manually: 
`command: /bin/tar -xvf /etc/sensu/ssl_generation/sensu_ssl_tool.tar -C /etc/sensu/ssl_generation/`

https://github.com/dhdanno/sensu-ansible/commit/5062ada2327faa10a5d55b7fad9f93983e0b3d53

Should be fixed properly in the 'unarchive' module when i get a chance.

**Comment by smuth4** [comment]
This should have been fixed in #25 , let me know if that's not the case
