### ISSUE TITLE
sensu master runs all checks

### ISSUE THREAD

**Issue by sst1xx** [cmacrae/ansible-sensu#44]
Hi,

sorry for dummies questions,

All definitions are copied into sensu master servers. And master server tries to run all checks.
I don't know how to avoid this behaviour.

May be smth wrong with my .j2 template?

{
  "checks": {
    "check_disk_usage": {
      "command": "{{ sensu_config_path }}/plugins/check-disk-usage.rb -w :::disk.warning|80::: -c :::disk.critical|90:::",

```
  "subscribers": {{ group_names | to_nice_json }},

  "interval": 60
}
```

  }
}

Thanks in advance
Vital

**Comment by smuth4** [comment]
In the template you have, `group_names` is going to be filled in with the master's groups. You need to either define the subscribers manually, or maybe use the `hostvars` magic variable to figure out some other node's group.

**Comment by sst1xx** [comment]
thank you very much!
you are right. I thought that it was possible to generate checks from j2 file in the same way as put plugin in https://github.com/sensu/sensu-ansible/blob/master/docs/dynamic_checks.md

The issue could be closed.

**Comment by smuth4** [comment]
Cool, glad I was able to help clear that up.
