### ISSUE TITLE
`dynamic_data_store` is undefined

### ISSUE THREAD

**Issue by cubranic** [cmacrae/ansible-sensu#45]
Log output, on Centos 7.2, Ansible 2.1.1.0:

```
TASK [cmacrae.sensu : Stash the Sensu SSL certs/keys] **************************
fatal: [sensu]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dynamic_data_store' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/cmacrae.sensu/tasks/ssl_generate.yml': line 47, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Stash the Sensu SSL certs/keys\n    ^ here\n"}
```

**Comment by smuth4** [comment]
That variable needs to be defined for this role to work. See
http://ansible-sensu.readthedocs.io/en/latest/dynamic_data/ and the rest of
the docs for more information.

**Comment by cubranic** [comment]
Very true, but it's not documented very visibly: there is no mention that it's essential for this role to run on any "quick-start" doc pages, or even on role_variables. I'll close this and open a separate issue for it, thank you.
