### ISSUE TITLE
Variables dynamic_data_store and static_data_store are under-documented

### ISSUE THREAD

**Issue by cubranic** [cmacrae/ansible-sensu#46]
There is no mention of "dynamic_data_store" and "static_data_store" on the "obvious" pages, like README.md and role variables. But the role won't run without those being defined _and_, in the case of static data store, having the right structure, i.e., "sensu/{checks,definitions,filters,handlers,mutators}". Those sub-directories have to be present, even if empty, or the role won't run.

**Comment by smuth4** [comment]
Agreed, there are two other open issues due to this. Unless someone else
wants to do it, I can put together a small PR sometime this weekend.

**Comment by smuth4** [comment]
Fixed in https://github.com/sensu/sensu-ansible/commit/f242892a5862950600c2ddd9a940887cba0318af

**Comment by smuth4** [comment]
Almost forgot the static_data_store, added that in https://github.com/sensu/sensu-ansible/commit/f32cd9ef606a44c645999f0f000af9d01912ad72
