### ISSUE TITLE
systemd[1]: Failed to start LSB: Sensu monitoring framework client.

### ISSUE THREAD

**Issue by relumer** [cmacrae/ansible-sensu#57]
hello
it finally builds ok with no errors during the process  but it fails to start

it fails with this error
 See 'systemctl status sensu-client.service' and 'journalctl -xn' for details.

and from logs i see this

systemctl status sensu-client.service
● sensu-client.service - LSB: Sensu monitoring framework client
   Loaded: loaded (/etc/init.d/sensu-client)
   Active: failed (Result: exit-code) since Wed 2016-12-07 17:22:12 EST; 6s ago
  Process: 20521 ExecStart=/etc/init.d/sensu-client start (code=exited, status=1/FAILURE)

Dec 07 17:22:12 debian3 sensu-client[20521]: Starting sensu-client: failed!
Dec 07 17:22:12 debian3 systemd[1]: sensu-client.service: control process exited, code=exited status=1
Dec 07 17:22:12 debian3 systemd[1]: Failed to start LSB: Sensu monitoring framework client.
Dec 07 17:22:12 debian3 systemd[1]: Unit sensu-client.service entered failed state.

any ideas.... ? @smuth4 @cmacrae

**Comment by smuth4** [comment]
What platform are you running this on? Is there any relevant information in /var/log/sensu/sensu-client.log?

Also, there's no need to tag us when creating an issue, I get notifications on all of them.

**Comment by relumer** [comment]
hi
sorry for the tags , i did not know
i am pushing the code from Ubuntu to Debian 8

this is the log 
root@debian1:~# tail /var/log/sensu/sensu-client.log 
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-6.0.0/lib/sensu/transport.rb:24:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/daemon.rb:253:in `setup_transport'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:451:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:19:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:18:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:22:in `load'
	from /opt/sensu/bin/sensu-client:22:in `<main>'

**Comment by smuth4** [comment]
It looks like there's some sort of exception going on, but you'll need to look at more than the last 10 lines to see it.

**Comment by smuth4** [comment]
I'm going to assume the cause of this issue was actually #56 and that it's been resolved. Please let me know if that's not the case.

**Comment by relumer** [comment]
Hi
i wish that was the cause but it was not.
If i set the machine that i run ansible from as master for redis,rabbit and sensu then the play finally executes with no errors . 
But if  i set under the host file different nodes to act as redis , then another machine as rabbit master and another one for sensu master then the play starts ok but gives errors at the end saying it can't start sensu-server on each machine.

as of now , i have 

[sensu_masters]
debian7 

[rabbitmq_servers]
debian8 
[redis_servers]
debian9 

[zones]
debian5 
debian4 


Below are the actual log files


fatal: [debian8]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": true, 
            "masked": null, 
            "name": "sensu-server", 
            "state": "started", 
            "user": false
        }
    }, 
    "msg": "Unable to start service sensu-server: Job for sensu-server.service failed. See 'systemctl status sensu-server.service' and 'journalctl -xn' for details.\n"

and

{"timestamp":"2016-12-11T17:02:00.592501-0500","level":"warn","message":"config file does not exist or is not readable","file":"/etc/sensu/config.json"}
{"timestamp":"2016-12-11T17:02:00.599813-0500","level":"warn","message":"ignoring config file","file":"/etc/sensu/config.json"}
{"timestamp":"2016-12-11T17:02:00.600415-0500","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2016-12-11T17:02:00.600497-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/api.json"}
{"timestamp":"2016-12-11T17:02:00.600566-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/transport.json"}
{"timestamp":"2016-12-11T17:02:00.600652-0500","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/transport.json","changes":{}}
{"timestamp":"2016-12-11T17:02:00.600879-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/rabbitmq.json"}
{"timestamp":"2016-12-11T17:02:00.601141-0500","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/rabbitmq.json","changes":{"rabbitmq":[null,{"ssl":{"cert_chain_file":"/etc/sensu/ssl/cert.pem","private_key_file":"/etc/sensu/ssl/key.pem"},"host":"debian7","port":5671,"vhost":"/sensu","user":"sensu","password":"REDACTED"}]}}
{"timestamp":"2016-12-11T17:02:00.601364-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/redis.json"}
{"timestamp":"2016-12-11T17:02:00.601460-0500","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/redis.json","changes":{"redis":[null,{"host":"debian7","port":6379}]}}
{"timestamp":"2016-12-11T17:02:00.636683-0500","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2016-12-11T17:02:00.638050-0500","level":"warn","message":"loaded extension","type":"filter","name":"occurrences","description":"filter events using event occurrences"}
{"timestamp":"2016-12-11T17:02:00.638772-0500","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2016-12-11T17:02:00.639525-0500","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2016-12-11T17:02:00.640191-0500","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2016-12-11T17:02:00.641069-0500","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2016-12-11T17:02:00.642720-0500","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `connect_server': unable to resolve server address: Inappropriate ioctl for device (EventMachine::ConnectionError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `bind_connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:653:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis.rb:48:in `connect_direct'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis.rb:71:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/daemon.rb:289:in `setup_redis'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:57:in `setup_connections'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:1163:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:32:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:31:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:22:in `load'
	from /opt/sensu/bin/sensu-server:22:in `<main>'

**Comment by smuth4** [comment]
That looks like an issue with your DNS, see https://groups.google.com/forum/#!topic/sensu-users/e-HkSZpAXfc

**Comment by relumer** [comment]
all of the jsons listed below had debian7 as the host ( debian7 is the sensu_master)
i replaced the hostname with ip and it seems to be working now :)

root@debian8:/etc/sensu/conf.d# ls
README.md  api.json  rabbitmq.json  redis.json	transport.json
root@debian8:/etc/sensu/conf.d# 


in var/log i now see these lines
{"timestamp":"2016-12-11T17:50:53.337152-0500","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}

but i will have to do some more debugging on these
