### ISSUE TITLE
sensu_pushover_userkey & sensu_pushover_token

### ISSUE THREAD

**Issue by relumer** [cmacrae/ansible-sensu#59]
Hi
i understand i have to create a host_vars directory and inside that a yaml file like debian7.yml to define pushover key and token.

Exactly how do i find where these files are located  so i can define their paths?

**Comment by smuth4** [comment]
As described in http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data, they are relative to the inventory file. Please make sure to check the official documentation before asking questions that aren't specific to this role.

**Comment by relumer** [comment]
hi 
my question was not how to write a hostvar file . I know how to do that.
I asked where is the path for the pushover and token keys

**Comment by relumer** [comment]
do i have to register somewhere to obtain such a pushover user and token ? this is what i don't understand

**Comment by smuth4** [comment]
That section is just an example to show how things are deployed, if you want to actually use the pushover plugin for notifications, you'll need to sign up for https://pushover.net/, which is a paid service.

**Comment by relumer** [comment]
ok i do not want to sign up for this at this time so how do i bypass this ? should i just delete the pushover files ans obtain something else from Sensu handlers instead ?

**Comment by smuth4** [comment]
Again, that section is just an example to demonstrate how things are deployed.

**Comment by relumer** [comment]
ok i set sensu include plugins to false and i will re run the role
thank you

**Comment by relumer** [comment]
ok no more errors for these :)
