### ISSUE TITLE
Unable to start service sensu-server

### ISSUE THREAD

**Issue by pleegor** [cmacrae/ansible-sensu#60]
Hi, 

I am running to setup sensu environment using sensu-ansible role. For testing purposes I disabled SSL. However, I get the following error at the end. 
`
fatal: [192.168.0.3]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": true,
            "masked": null,
            "name": "sensu-client",
            "state": "started",
            "user": false
        }
    },
    "msg": "Unable to start service sensu-client: Job for sensu-client.service failed because the control process exited with error code. See \"systemctl status sensu-client.service\" and \"journalctl -xe\" for details.\n"
}
	to retry, use: --limit @/root/playbook.retry
`

Any idea what could cause this error?

**Comment by cmacrae** [comment]
Have you followed the advice of the output you pasted above?
>`See "systemctl status sensu-client.service" and "journalctl -xe" for details."`

**Comment by pleegor** [comment]
@cmacrae thanks for jumping to help. When I am trying to check sensu-client status i get the following: 
`ansible -m command -a "systectl sensu-client.service status" 192.168.0.3
192.168.0.3 | FAILED | rc=2 >>
[Errno 2] No such file or directory`

I believe somehow service is not being installed.

**Comment by cmacrae** [comment]
Hmm, okay, we'll have you hopped on and poked around in an interactive shell? It'd be much easier to debug.

I'd recommend SSH'ing in and checking if the service files are there in there respective locations (depending on the distro you're running) and if they are there, what their contents are.

**Comment by smuth4** [comment]
`systectl` maybe needs to be `systemctl` in that command?

**Comment by cmacrae** [comment]
Yep 👆🏻 Didn't notice that

**Comment by somabc** [comment]
Just installed and have the same problem. CentOS 7.

sensu-server.service - LSB: Sensu monitoring framework server
   Loaded: loaded (/etc/rc.d/init.d/sensu-server; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-12-14 13:35:04 GMT; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 15327 ExecStart=/etc/rc.d/init.d/sensu-server start (code=exited, status=1/FAILURE)

**Comment by cmacrae** [comment]
Right, could people provide a bit more debugging? Logs, execution of startup commands using debug flags/foregrounding?

**Comment by abednarik** [comment]
This kind of errors are probably related to configuration errors. Check /var/log/sensu/sensu-server.log or post it here, so anyone can help.

**Comment by RamyaGowda397** [comment]
hi i am facing the same issue , and here is my log details


{"timestamp":"2017-10-26T10:08:07.810426+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:08:27.810760+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:08:47.812352+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:09:07.812908+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:09:27.812810+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:09:47.814396+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:10:07.813879+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:10:27.814195+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:10:47.814579+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:11:07.816310+0530","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-10-26T10:11:19.456269+0530","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2017-10-26T10:11:19.456372+0530","level":"warn","message":"stopping"}
{"timestamp":"2017-10-26T10:11:19.456400+0530","level":"info","message":"completing work in progress","in_progress":{}}
{"timestamp":"2017-10-26T10:11:19.957073+0530","level":"warn","message":"stopping reactor"}
{"timestamp":"2017-10-26T10:11:21.460872+0530","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2017-10-26T10:11:21.460962+0530","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2017-10-26T10:11:21.461011+0530","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2017-10-26T10:11:21.461105+0530","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/client.json","changes":{"client":{"name":["localhost","sensu-server"],"environment":[null,"management"],"socket":[null,{"bind":"127.0.0.1","port":3030}]}}}
{"timestamp":"2017-10-26T10:11:21.461160+0530","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/api.json"}
{"timestamp":"2017-10-26T10:11:21.461221+0530","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/api.json","changes":{"api":{"bind":[null,"0.0.0.0"]}}}
{"timestamp":"2017-10-26T10:11:21.461268+0530","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/cpu_threshold.json"}
{"timestamp":"2017-10-26T10:11:21.461338+0530","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/cpu_threshold.json","changes":{"checks":{"disk_capacity":[null,{"command":"check-graphite-data.rb -t 'highestCurrent(*.disk.*.capacity,1)' -w 5 -c 6","standalone":true,"interval":30}]}}}
{"timestamp":"2017-10-26T10:11:21.461400+0530","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/cpu_metrics.json"}
{"timestamp":"2017-10-26T10:11:21.461478+0530","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/cpu_metrics.json","changes":{"checks":{"cpu_usage":[null,{"command":"check-cpu-usage.rb -c 2 -w 1","standalone":true,"interval":10}]}}}
{"timestamp":"2017-10-26T10:11:21.461536+0530","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/tcp_socket.json"}
{"timestamp":"2017-10-26T10:11:21.461633+0530","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/tcp_socket.json","changes":{"handlers":{"tcp_socket":[null,{"type":"tcp","socket":{"host":"localhost","port":6000}}]}}}
{"timestamp":"2017-10-26T10:11:21.461680+0530","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/default_handler.json"}
{"timestamp":"2017-10-26T10:11:21.461726+0530","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/default_handler.json","changes":{}}
{"timestamp":"2017-10-26T10:11:21.461770+0530","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/transport_events.json"}
{"timestamp":"2017-10-26T10:11:21.461887+0530","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/transport_events.json","changes":{"handlers":{"transport":[null,{"type":"transport","pipe":{"type":"direct","name":"events"}}]}}}

**Comment by jaredledvina** [comment]
Hey @pleegor,

Sorry for the delay, if you're still hitting this issue, can you comment here with the error logs from `/var/log/sensu/sensu-client.log` as well as the RabbitMQ logs. 

@RamyaGowda397 - Were you able to resolve that error? I _think_ that indicates that the `sensu-client` cannot communicate to RabbitMQ, can you verify that RabbitMQ is up and running and that the configured credentials are correct in the `sensu-client` configuration?

**Comment by jaredledvina** [comment]
Closing this out due to inactivity. Let me know if you'd like this to be re-visited, more than happy to reopen.
