### ISSUE TITLE
Stash the Sensu SSL certs/keys]

### ISSUE THREAD

**Issue by somabc** [cmacrae/ansible-sensu#61]
TASK [cmacrae.sensu : Stash the Sensu SSL certs/keys] **************************
fatal: [ee-sensu.ee.ic.ac.uk]: FAILED! => {"failed": true, "msg": "failed to transfer file to /etc/ansible/data/dynamic/ee-sensu.ee.ic.ac.uk/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem:\n\n/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem: No such file or directory\n"}

dynamic_data_store: /etc/ansible/data/dynamic is defined in all.yml

**Comment by cmacrae** [comment]
Have you checked your dynamic data store to see if the data does exist?
`No such file or directory` would imply it doesn't

**Comment by somabc** [comment]
There is nothing in the dynamic data store.  The folders are created properly but no certificates. 
on the ansible host /etc/ansible/data/dynamic/ee-sensu.ee.ic.ac.uk/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/ is empty

On the sensu_master /etc/sensu/ssl_generation/sensu_ssl_tool
[root@ee-sensu sensu_ssl_tool]# tree
.
├── client
│   ├── cert.pem
│   ├── keycert.p12
│   ├── key.pem
│   └── req.pem
├── sensu_ca
│   ├── cacert.cer
│   ├── cacert.pem
│   ├── certs
│   │   ├── 01.pem
│   │   └── 02.pem
│   ├── index.txt
│   ├── index.txt.attr
│   ├── index.txt.attr.old
│   ├── index.txt.old
│   ├── openssl.cnf
│   ├── private
│   │   └── cakey.pem
│   ├── serial
│   └── serial.old
├── server
│   ├── cert.pem
│   ├── keycert.p12
│   ├── key.pem
│   └── req.pem
└── ssl_certs.sh

**Comment by somabc** [comment]
oh I see am using ansible/data/dynamic instead of ansible/config/data/dynamic. I will change that and test!

**Comment by cmacrae** [comment]
👍🏻

**Comment by somabc** [comment]
Sorry it is the same problem cacert.pem is reported as missing.

**Comment by somabc** [comment]
after running with -vvvv

TASK [cmacrae.sensu : Stash the Sensu SSL certs/keys] **************************
task path: /etc/ansible/roles/cmacrae.sensu/tasks/ssl_generate.yml:36
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/stat.py
<ee-sensu.ee.ic.ac.uk> ESTABLISH SSH CONNECTION FOR USER: None
<ee-sensu.ee.ic.ac.uk> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r ee-sensu.ee.ic.ac.uk '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606 `" && echo ansible-tmp-1481726640.01-86365754250606="` echo $HOME/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606 `" ) && sleep 0'"'"''
<ee-sensu.ee.ic.ac.uk> PUT /tmp/tmpXQ4WGZ TO /root/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606/stat.py
<ee-sensu.ee.ic.ac.uk> SSH: EXEC scp -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r /tmp/tmpXQ4WGZ '[ee-sensu.ee.ic.ac.uk]:/root/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606/stat.py'
<ee-sensu.ee.ic.ac.uk> ESTABLISH SSH CONNECTION FOR USER: None
<ee-sensu.ee.ic.ac.uk> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r ee-sensu.ee.ic.ac.uk '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606/ /root/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606/stat.py && sleep 0'"'"''
<ee-sensu.ee.ic.ac.uk> ESTABLISH SSH CONNECTION FOR USER: None
<ee-sensu.ee.ic.ac.uk> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt ee-sensu.ee.ic.ac.uk '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606/stat.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1481726640.01-86365754250606/" > /dev/null 2>&1 && sleep 0'"'"''
<ee-sensu.ee.ic.ac.uk> FETCH /etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem TO /etc/ansible/config/data/dynamic/ee-sensu.ee.ic.ac.uk/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem
<ee-sensu.ee.ic.ac.uk> SSH: EXEC scp -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r /etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem '[ee-sensu.ee.ic.ac.uk]:/etc/ansible/config/data/dynamic/ee-sensu.ee.ic.ac.uk/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem'
fatal: [ee-sensu.ee.ic.ac.uk]: FAILED! => {
    "failed": true, 
    "msg": "failed to transfer file to /etc/ansible/config/data/dynamic/ee-sensu.ee.ic.ac.uk/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem:\n\nExecuting: program /usr/bin/ssh host ee-sensu.ee.ic.ac.uk, user (unspecified), command scp -v -t /etc/ansible/config/data/dynamic/ee-sensu.ee.ic.ac.uk/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem\nOpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 61771\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\n/etc/sensu/ssl_generation/sensu_ssl_tool/sensu_ca/cacert.pem: No such file or directory\n"

**Comment by somabc** [comment]
cat all.yml 
dynamic_data_store: /etc/ansible/config/data/dynamic
rabbitmq_host: ee-sensu.ee.ic.ac.uk
redis_host: ee-sensu.ee.ic.ac.uk
sensu_api_host: ee-sensu.ee.ic.ac.uk

**Comment by somabc** [comment]
It's failing specifically at server/key.pem. If I copy the files over manually it still fails at key.pem

There are some other files in the server folder.
-rw-r--r--. 1 root root 1.1K Dec 14 18:01 cert.pem
-rw-r--r--. 1 root root 2.3K Dec 14 18:01 keycert.p12
-rw-r--r--. 1 root root 1.7K Dec 14 18:01 key.pem
-rw-r--r--. 1 root root  907 Dec 14 18:01 req.pem

ASK [cmacrae.sensu : Stash the Sensu SSL certs/keys] **************************
ok: [ee-sensu.ee.ic.ac.uk] => (item=sensu_ca/cacert.pem)
ok: [ee-sensu.ee.ic.ac.uk] => (item=server/cert.pem)
fatal: [ee-sensu.ee.ic.ac.uk]: FAILED! => {"failed": true, "msg": "failed to transfer file to /etc/ansible/config/data/dynamic/ee-sensu.ee.ic.ac.uk/etc/sensu/ssl_generation/sensu_ssl_tool/server/key.pem:\n\n/etc/sensu/ssl_generation/sensu_ssl_tool/server/key.pem: No such file or directory\n"}
        to retry, use: --limit @/etc/ansible/sensu_masters.retry

**Comment by somabc** [comment]
Switched ansible.cfg to use SFTP instead of SCP.

That works.
