### ISSUE TITLE
Remote plugin deployment and Dynamic Check Deployment

### ISSUE THREAD

**Issue by dimthe** [cmacrae/ansible-sensu#64]
Hello 

I am reading the docs at the moment and i have a question about Dynamic Check Deployment. In the readme it shows a tree list command showing several check scripts to check each of your servers. To clone this scenario do i have to manually download sensu plugins from sensu official pluging page and copy them in dynamic and static datastore ?

in defaults/main i have these lines

sensu_remote_plugins: 
  - graphite
  - process-checks
  - sensu-plugins-disk-usage

thanks

**Comment by smuth4** [comment]
No, including them in `sensu_remote_plugins` is enough, then you'll be able to find the scripts in `/opt/sensu/embedded/bin/`. The static data store is for all the manually-downloaded checks, and the dynamic data store isn't used for either of those operations.

**Comment by dimthe** [comment]
ok , i have just included 3 plugins in sensu_remote_plugins like i said above

the play gives this error 

ll 2>&1 && sleep 0'
fatal: [debian1 -> localhost]: FAILED! => {
    "changed": false,
    "cmd": [
        "ls",
        "/etc/ansible/data/static/sensu/checks"
    ],
    "delta": "0:00:00.005980",
    "end": "2017-01-13 00:18:01.995692",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "ls /etc/ansible/data/static/sensu/checks",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 2,
    "start": "2017-01-13 00:18:01.989712",
    "stderr": "ls: cannot access '/etc/ansible/data/static/sensu/checks': No such file or directory",
    "stdout": "",
    "stdout_lines": [],
    "warnings": []

what do you think causing this ?

**Comment by cmacrae** [comment]
Hi @dimthe - read the output fully, the answer is there :)
```
"stderr": "ls: cannot access '/etc/ansible/data/static/sensu/checks': No such file or directory",
```

This role assumes users will be utilising the primary intended deployment method of checks, which is the use of the static datastore. I wrote support for the remote plugins as an added extra.  

Perhaps, if I have some time, I may go over it and add some logic for the presence (or lack thereof) of the `checks` directory, for those not intending to use the static datastore for checks.

**Comment by dimthe** [comment]
Hello @cmacrae   

that path exists in the computer i am running ansible ( with your role ) but not on each other server.
Do i have to manually create that directories in each host ?

**Comment by cmacrae** [comment]
@dimthe Oh? That's not right... 🤔 
No, it shouldn't be necessary to create it on each host, that action (the `ls` to register the checks) should be local only.

EDIT: See https://github.com/sensu/sensu-ansible/blob/master/tasks/plugins.yml#L20

**Comment by dimthe** [comment]
ok im confused now and stuck

i have this path in the pc im executing ansible from

ls /etc/ansible/data/
dynamic  static


what else can i check @cmacrae  


here is a tree list

tree /etc/ansible/data/static/
/etc/ansible/data/static/
└── sensu
    └── checks

2 directories, 0 files



should the directories be empty?  datastore is defined as it should as well
static_data_store: "/etc/ansible/data/static"

**Comment by cmacrae** [comment]
@dimthe So, is the `checks` directory present in `/etc/ansible/data/static/` on the system you're running Ansible from?

**Comment by dimthe** [comment]
@cmacrae  yes it is 

tree /etc/ansible/data/static/
/etc/ansible/data/static/
└── sensu
    └── checks

2 directories, 0 files

**Comment by smuth4** [comment]
The checks directory should be inside the sensu directory.

**Comment by dimthe** [comment]
Hi , 
thats how it is 

ls /etc/ansible/data/static/sensu/checks/

**Comment by dimthe** [comment]
figured this out so closing for good
