### ISSUE TITLE
tasks/ssl.yml

### ISSUE THREAD

**Issue by dimthe** [cmacrae/ansible-sensu#66]
Hello

Here is my hosts file

[sensu_masters]
debian21  

[redis_servers]
debian20  

[rabbitmq_servers] 
debian19   

[zones]
debian22 
debian23
debian24
debian25

in main.yml i have sensu master to false as well as redis server set to false and the play stops with errors about SSLs

Do i have to create self signed certs and tell the role where to look for these ?

**Comment by dimthe** [comment]
i see ssl.yml is being executed first and ssl_generate.yml later. Shouldn;t this be reversed ?

**Comment by smuth4** [comment]
Correct, the role creates SSL certs on any host where sensu_master is true, so if that's not the case, you'll have to generate your own.

**Comment by dimthe** [comment]
Hi

i have not used my own ssl , just what the role generated using the sensu tool but i get these errors for every host
here is an example

failed: [debian21] (item={u'dest': u'key.pem', u'src': u'/etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem'}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": false, 
            "content": null, 
            "delimiter": null, 
            "dest": "/etc/sensu/ssl/key.pem", 
            "directory_mode": null, 
            "follow": false, 
            "force": true, 
            "group": "root", 
            "mode": null, 
            "original_basename": null, 
            "owner": "root", 
            "regexp": null, 
            "remote_src": true, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem", 
            "unsafe_writes": null, 
            "validate": null
        }
    }, 
    "item": {
        "dest": "key.pem", 
        "src": "/etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem"
    }, 
    "msg": "Source /etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem not found"
}
failed: [debian19] (item={u'dest': u'key.pem', u'src': u'/etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem'}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": false, 
            "content": null, 
            "delimiter": null, 
            "dest": "/etc/sensu/ssl/key.pem", 
            "directory_mode": null, 
            "follow": false, 
            "force": true, 
            "group": "root", 
            "mode": null, 
            "original_basename": null, 
            "owner": "root", 
            "regexp": null, 
            "remote_src": true, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem", 
            "unsafe_writes": null, 
            "validate": null
        }
    }, 
    "item": {
        "dest": "key.pem", 
        "src": "/etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem"
    }, 
    "msg": "Source /etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem not found"

**Comment by dimthe** [comment]
hi
what can i check to see why i get these errors ? 

as far as i can tell , the files are all there

This is just for one of the hosts it can not copy over 

│   │                                               └── key.pem
│   ├── debian21
│   │   ├── etc
│   │   │   └── sensu
│   │   │       └── ssl_generation
│   │   │           └── sensu_ssl_tool
│   │   │               ├── client
│   │   │               │   ├── cert.pem
│   │   │               │   └── key.pem
│   │   │               ├── sensu_ca
│   │   │               │   └── cacert.pem
│   │   │               └── server
│   │   │                   ├── cert.pem
│   │   │                   └── key.pem

**Comment by smuth4** [comment]
From that tree output, it looks like `/etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/key.pem` doesn't exist, and instead key.pem is at `/etc/ansible/data/dynamic/debian21/etc/client/key.pem`. Did you override any of the variables that effect the SSL path?

Also, if you're getting errors, please post those first, so we can avoid the XY problem: http://mywiki.wooledge.org/XyProblem

**Comment by dimthe** [comment]
Hello smuth4

key.pem is where it should be 

$ ls /etc/ansible/data/dynamic/debian21/etc/sensu/ssl_generation/sensu_ssl_tool/client/
cert.pem  key.pem


and this is the ssl.yml  which i have not messed with

`---
# tasks/ssl.yml: Deploy the client SSL cert/key to client systems

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure Sensu SSL directory exists
    file:
      dest: "{{ sensu_config_path }}/ssl"
      state: directory
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"

  - include: ssl_generate.yml
    when: sensu_ssl_gen_certs

  - name: Deploy the Sensu client SSL cert/key
    copy:
      src: "{{ item.src }}"
      owner: "{{ sensu_user_name }}"
      remote_src: "{{ sensu_ssl_deploy_remote_src }}"
      group: "{{ sensu_group_name }}"
      dest: "{{ sensu_config_path }}/ssl/{{ item.dest }}"
    with_items:
     - {src: "{{ sensu_ssl_client_cert }}", dest: cert.pem}
     - {src: "{{ sensu_ssl_client_key }}", dest: key.pem}
    notify: restart sensu-client service`

**Comment by smuth4** [comment]
This seems very first similar to the first issue you reported, where a file existed but ansible wasn't seeing it. What was the solution to that problem?

Also, please either format the tree output properly, or use a tool like `find` which doesn't need to be formatted.

**Comment by dimthe** [comment]
ok since all these machines are virtual i will redo everything and repost with any issues ( hopefully none )

i honestly can't remember how i solved that because i have been messing with this for 2 days straight and i tried many things but i think it was my ansible version. 
i now have 2.2.1.0

**Comment by dimthe** [comment]
i downgraded ansible to ansible --version
ansible 2.2.0.0
and the ssl issue is now resovled
