### ISSUE TITLE
deploy everything to one host , Uchiwa says sensu-api does not run

### ISSUE THREAD

**Issue by dimthe** [cmacrae/ansible-sensu#67]
Hi
to ease things i followed the readme docs to deploy everything to one host. My plan is to have one host to act as sensu master , redis and rabbitmq-server  and to monitor using plugins other hosts in my lan. 
For starters   i set sensu master , redis and rabbitmq server to false in the main.yml.  In group_vars/all.yml i defined all 3 variables like the docs show to point to the IP of my intended sensu master host like so 
rabbitmq_host: 192.168.1.95
redis_host: 192.168.1.95
sensu_api_host: 192.168.1.95

In group_vars i also created 3 yml files named rabbitmq_servers , redis_server  and sensu_masters , like the docs show and inside each file there is a value : true accordingly . 

Do all of the above seem correct? I think they do . 

In my hosts file , i have defined 
[sensu_servers] 
the above host
[redis_servers]
same above host
[rabbitmq_servers]
the above host again

[zones]
several different hosts go here

So , one host will act as sensumaster,redis and rabbitmq and will deploy plugins to everything under [zones]

How do you execute such playbook?
 
hosts: all

or

hosts: sensu_masters

i tried both , and although the play finishes , the Uchiwa dashboard says sensu-api is not running. I sshed into my intended sensumaster and sensu api was running so it must be something else

some help/ideas?

thank you

**Comment by dimthe** [comment]
any ideas.. ?

**Comment by smuth4** [comment]
What endpoint is in the Uchiwa configs?

**Comment by dimthe** [comment]
Hello @smuth4 

do you mean this ?


cat /etc/sensu/uchiwa.json 
{
 "sensu": [
   {
       "name": "",
       "host": "192.168.1.105",
       "ssl": false,
       "port": 4567,
       "user": "admin",
       "pass": "secret",
       "path": "",
       "timeout": 5000
   }
 ],
 "uchiwa": {
   "users": [
    {
        "password": "admin", 
        "username": "admin"
    }
],
   "port": 3000,
   "refresh": 5
  }
}

**Comment by rwillmer** [comment]
I had a similar problem, which was caused by the API not being able to talk to the transport, due to a IPv4/IPv6 problem. Which I reported as https://github.com/sensu/sensu/issues/1685

If your config files use names which require DNS resolution anywhere, try changing those to IP addresses; it may fix your problem.

**Comment by jaredledvina** [comment]
Hey @dimthe,

Sorry for the delay, are you still hitting this problem?

**Comment by jaredledvina** [comment]
Closing this out due to inactivity. Let me know if you'd like this to be re-visited, more than happy to reopen.
