### ISSUE TITLE
one host to rule them all , from the docs , question

### ISSUE THREAD

**Issue by dimthe** [cmacrae/ansible-sensu#68]
reading the docs , there is an example where you set up one host to act as sensu master , redis and rabbitmq. When utilizing such a set up , how do you deploy the plugins ( defined in defaults/main.yml ) to the rest of the hosts in an infrastructure ?

**Comment by jaredledvina** [comment]
Hey @dimthe, 

Sorry for the delay! You can use the `sensu_remote_plugins` variable as a list to install plugins on remote clients. Let me know if you have any other questions!

**Comment by jaredledvina** [comment]
Closing this out due to inactivity. Let me know if you'd like this to be re-visited, more than happy to reopen.
