### ISSUE TITLE
Checks are not updated by sensu

### ISSUE THREAD

**Issue by dancb10** [cmacrae/ansible-sensu#70]
Hello,
I have two different issues with my setup:
First, if I try to modify any sensu checks with ansible, the checks are not updated and still show the old info. For example, I've modified the threshold for some checks but I still see them in uchiwa showing with the old config.
I've tried to restart all components (server,api,redis) but i still have the same issue. How is sensu reading the checks.json file that's generated by ansible?

When I add new checks, they are not automatically added to the Uchiwa interface. I have to restart at least the redis database or even uchiwa. When I do restart them they appear in the checks tab in uchiwa but not on machines and I have to schedule them manually

**Comment by smuth4** [comment]
The JSON files should get generated into /etc/sensu/conf.d/, which the various client/server/api services should pick up automatically. I would trying temporarily running the server in the foreground to make sure it's reading all the check files correctly. The only other thing I can think of is if you're using standalone checks, the server may not be aware of the checks until the client either sends a result or it's requested manually.

**Comment by jaredledvina** [comment]
Hey @dancb10, 

Sorry for the delay here! Are you still facing this issue?

**Comment by jaredledvina** [comment]
Closing this out due to inactivity. Let me know if you'd like this to be re-visited, more than happy to reopen.
