### ISSUE TITLE
Separate Sensu Server and API?

### ISSUE THREAD

**Issue by hany** [cmacrae/ansible-sensu#72]
Is it possible to run the Server and API components on different instances? From the looks of the docs, it appears the two always get deployed side-by-side.

**Comment by haphan** [comment]
Don't think it is possible. Plus, Sensu enterprise bundle `sensu-server` and `sensu-api` in `sensu-enterprise` package.

**Comment by cwjohnston** [comment]
@hany I can't speak to the capabilities of this ansible playbook directly, but in general running `sensu-server` and `sensu-api` daemons on different compute instances is supported. Doing so adds additional complexity which is sometimes better avoided. As @haphan points out, `sensu-enterprise` avoids this complexity by providing both the API and event processing in a single process.

**Comment by hany** [comment]
OK, thanks for the update. I was more curious if the two processes need to be scaled independently, how would that be achieved, but it sounds like they are more interconnected than initially thought.

**Comment by jaredledvina** [comment]
Hey @hany, 

Sorry for the delay here, I took a look through this role and currently, both the `sensu-server` and `sensu-api` will be deployed if you configure `sensu_master: true` and there's no support to independently deploy them. 

Would that feature be useful for you? I can try to put something together to support that if so. 

> I was more curious if the two processes need to be scaled independently, how would that be achieved

Generally speaking, the requirements of the `sensu-server` and `sensu-api` will differ. In my experience, the API will need fewer system resources than the server but, that'll strongly depend on your environment setup. Personally, I co-locate both services together to make the deployment, configuration, and maintenance saner. 

Let me know what you thing!

**Comment by hany** [comment]
Hey @jaredledvina,

> Generally speaking, the requirements of the sensu-server and sensu-api will differ. In my experience, the API will need fewer system resources than the server but, that'll strongly depend on your environment setup. Personally, I co-locate both services together to make the deployment, configuration, and maintenance saner.

Yes, this is what we've observed as well. The two processes do have different performance profiles and do need to scale independently. Right now, we're just running both services together on every machine, but it would be best to have them split at some point.

**Comment by jaredledvina** [comment]
I'm going to close this out as "unsupported" currently with this Ansible role. If anyone is interested in adding in support for deploying Sensu Server and Sensu API separately, feel free to open a Pull Request.
