### ISSUE TITLE
Redis PIDFile Not Found (Ubuntu 16.10)

### ISSUE THREAD

**Issue by hyperatom** [cmacrae/ansible-sensu#75]
Testing this role on Ubuntu 16.10 x64 with redis repository left as default, I found that the PIDFile setting in files/redis_systemd.service needs to refer to redis-server.pid instead of redis.pid.

**Comment by aharden** [comment]
Also found on Ubuntu 16.04.

**Comment by smuth4** [comment]
That seems odd, considering the `--pidfile` parameter is being properly passed to start-stop-daemon. Of course, that only raises the question of why start-stop-daemon is being used inside systemd in the first place.
