### ISSUE TITLE
Sensu Services failed to start

### ISSUE THREAD

**Issue by keeshqs** [cmacrae/ansible-sensu#76]
Hi,

We are running a feasibility study for Sensu and ELK platform and we were finally able to set up Sensu after running into some minor issues., right now we can't start / restart sensu services for some reason and we've been stuck to this for a day now, So I hope you could give us some advice. We would truly appreciate your response. 

**Expected Behavior:**
Sensu-Server will be started
Sensu-api will be started

**Current Behavior:**
After initializing startup, the following message is returned:

"Job for sensu-server.service failed because the control process exited with error code. See "systemctl status sensu-server.service" and "journalctl -xe" for details."

**> status sensu-server.service **

● sensu-server.service - LSB: Sensu monitoring framework server
Loaded: loaded (/etc/init.d/sensu-server; bad; vendor preset: enabled)
Active: failed (Result: exit-code) since Mon 2017-02-27 13:38:21 GMT; 11s ago
Docs: man:systemd-sysv-generator(8)
Process: 9041 ExecStop=/etc/init.d/sensu-server stop (code=exited, @@@status=0/SUCCESS)
Process: 21292 ExecStart=/etc/init.d/sensu-server start (code=exited, status=1/FAILURE)

Feb 27 13:38:20 systemd[1]: Stopped LSB: Sensu monitoring framework server.
Feb 27 13:38:20 systemd[1]: Starting LSB: Sensu monitoring framework server...
Feb 27 13:38:20 sensu-server[21292]: * Starting sensu-server
Feb 27 13:38:21 sensu-server[21292]: ...fail!
Feb 27 13:38:21 systemd[1]: sensu-server.service: Control process exited, code=exited status=1
Feb 27 13:38:21 systemd[1]: Failed to start LSB: Sensu monitoring framework server.
Feb 27 13:38:21 systemd[1]: sensu-server.service: Unit entered failed state.
Feb 27 13:38:21 systemd[1]: sensu-server.service: Failed with result 'exit-code'
(fyi, the same happens when trying to restart other sensu services)

**> $ tail /var/log/sensu/sensu-client.log**

{"timestamp":"2017-02-27T12:52:26.172506+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T12:52:46.173374+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:09:46.226619+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:10:06.227236+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:10:26.228142+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:10:46.229256+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:11:06.230354+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:11:26.231242+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:11:46.232049+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-02-27T13:12:06.233025+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}

**Environment**

Sensu version used: Sensu 0.27
Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04 LTS
Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ 3.6.6

**Comment by smuth4** [comment]
That error means sensu isn't able to connect to the transport. Do the hostname and ports in /etc/sensu/conf.d/rabbitmq.json match up with where your rabbitmq server is located? Are all the appropriate ports opened up?

**Comment by keeshqs** [comment]
Thank you so much for your response! :) This has actually been resolved by moving uchiwa.json from etc/sensu/conf.d to etc/sensu
