### ISSUE TITLE
Compatibility with sensu enterprise

### ISSUE THREAD

**Issue by haphan** [cmacrae/ansible-sensu#80]
I am extending this repo so that it can deploy sensu enterprise. 

Do you guys think it would be interesting to merge it back to `sensu/sensu-ansible`?

**Comment by haphan** [comment]
See related wip pull request #82

**Comment by smuth4** [comment]
👍 in concept, there are a couple details regarding compatibility with non-enterprise users in the PR I'll note.

**Comment by haphan** [comment]
Close since #82 is merged to master.
