### ISSUE TITLE
Highly available Uchiwa

### ISSUE THREAD

**Issue by KITSDanMassie** [cmacrae/ansible-sensu#86]
In order to make Uchiwa highly available certificates need to be generated and provided in the uchiwa config https://docs.uchiwa.io/guides/high-availability/

The uchiwa config block in the template currently does not allow these to be specified https://github.com/sensu/sensu-ansible/blob/master/templates/uchiwa_config.json.j2

**Comment by smuth4** [comment]
Fixed in b6f3313a8e4f134f843b5d66a0aa95589440dac2
