### ISSUE TITLE
'dict object' has no attribute 'sensu_masters'

### ISSUE THREAD

**Issue by ssirobertreilly** [cmacrae/ansible-sensu#88]
All i am facing the following issue after following the docs to install on a single node. my config is as follows:
inventory:
```

cat inventory/sensu.yml
[sensu_masters]
sensu.master

[rabbitmq_servers]
sensu.master

[redis_servers]
sensu.master
```

group_vars:
```

cat group_vars/all.yml
rabbitmq_host: sensu
redis_host: sensu
sensu_api_host: sensu
dynamic_data_store: /etc/ansible/config/data/dynamic
```

host_vars:
```
cat host_vars/sensu.yml
sensu_master: true
sensu_include_dashboard: true
rabbitmq_server: true
redis_server: true
```

but i continue to get the following error
`fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ sensu_ssl_tool_base_path }}/client/cert.pem: {{ dynamic_data_store }}/{{ groups['sensu_masters'][0] }}{{ sensu_master_config_path }}/ssl_generation/sensu_ssl_tool: {{ hostvars[groups['sensu_masters'][0]]['sensu_config_path'] | default('/etc/sensu') }}: 'dict object' has no attribute 'sensu_masters'"}`

ansible version
```[vagrant@sensu ~]$ ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

sensu version 
```0.29.0```
I have looked though the other issues  and was not able to find a resolution, I am fairly new to ansible but not sensu and have deployed it before with chef. thanks in advance for any help you can provide.
rr

**Comment by ssirobertreilly** [comment]
bump ?

**Comment by smuth4** [comment]
Sorry about that, it looks like you don't have any `sensu_masters` defined, despite your inventory indicating otherwise. Can you confirm `ansible --list-hosts sensu_masters` returns at least one host? If not, you'll want double check that `/etc/ansible/ansible.cfg` is pulling in the correct inventory files.

**Comment by ssirobertreilly** [comment]
Hi no worries!
```
ansible --list-hosts sensu_masters -i inventory
  hosts (1):
    sensu.master
```

sensu.master is the name of the host i am using, and I am currently testing in test-kitchen

I just reread your comment I wonder if the inventory is not being picked up by test-kitchen, i will test it against a real host.

**Comment by ssirobertreilly** [comment]
it worked against a real host but did not install rabbitmq so sensu does not start. the only way I could get it to install rabbitmq was to remove the when statement. ( this is obviously not a viable solution) was trying to get it to install

**Comment by ssirobertreilly** [comment]
now there is a sensu log entry 
```
"timestamp":"2017-06-21T09:20:15.836313-0400","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2017-06-21T09:20:15.895905-0400","level":"warn","message":"transport connection error","reason":"tcp connection lost"}
{"timestamp":"2017-06-21T09:20:17.898186-0400","level":"warn","message":"transport connection error","reason":"tcp connection lost"}
{"timestamp":"2017-06-21T09:20:17.898328-0400","level":"warn","message":"transport connection error","reason":"possible authentication failure. wrong credentials?","user":"sensu"}
{"timestamp":"2017-06-21T09:20:21.898203-0400","level":"warn","message":"transport connection error","reason":"tcp connection lost"}
{"timestamp":"2017-06-21T09:20:21.898328-0400","level":"warn","message":"transport connection error","reason":"possible authentication failure. wrong credentials?","user":"sensu"}
{"timestamp":"2017-06-21T09:20:27.898460-0400","level":"warn","message":"transport connection error","reason":"tcp connection lost"}
{"timestamp":"2017-06-21T09:20:27.898596-0400","level":"warn","message":"transport connection error","reason":"possible authentication failure. wrong credentials?","user":"sensu"}
```
