### ISSUE TITLE
Static Data Store versus sensu_remote_plugins

### ISSUE THREAD

**Issue by vialcollet** [cmacrae/ansible-sensu#9]
Hi and congratulations for this fantastic role and nice documentation.
There is one thing I don't understand though... I see that there is a sensu_remote_plugins variable that we can set in order to define which plugins we want to deploy. At the same time, in the static data store, we can also set some checks on a per group basis.
How these two methods interact? Do we need both? 
Thanks in advance for enlightening me on this topic :)

**Comment by cmacrae** [comment]
Hi @vialcollet :wave: 
Thanks for the kind words!

The `sense_remote_plugins` variable is completely independent from the plugins deployed via the data store. It's simply to expose the option to install plugins from Ruby Gems via the `sensu-install` command.
They can both be used at the same time, or on their own :+1: 

Let me know if I can explain it any further, don't hesitate to ask any further questions.

**Comment by vialcollet** [comment]
Oh, ok ! So basically I can use the sensu_remote_plugin to deploy plugins from Ruby Gem and if I had my own checks I could use the Static Data Store.
Thanks I think I got the concept!
I'll let you know if I have any further questions.
And thanks a lot for the quick answer.

**Comment by cmacrae** [comment]
Yep, exactly :) No problem, thanks for using the role
