### ISSUE TITLE
Ubuntu 14.04LTS no https transport

### ISSUE THREAD

**Issue by kevit** [cmacrae/ansible-sensu#90]
`
FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 213.196.39.216 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_ZI1hPK/ansible_module_apt_repository.py\", line 565, in <module>\r\n    main()\r\n  File \"/tmp/ansible_ZI1hPK/ansible_module_apt_repository.py\", line 553, in main\r\n    cache.update()\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: E:The method driver /usr/lib/apt/methods/https could not be found.\r\n", "msg": "MODULE FAILURE", "rc": 0}
`

Next run
`
TASK [cmacrae.sensu : Ensure Sensu is installed] ********************************************************************************************************************************************************************************************************************************************************************
fatal: []: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'sensu' is available"}
`

on the node
`
root@box:~# apt-get update
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
`

Ill update with the patch shortly

**Comment by DavidVentura** [comment]
you need to install ca-certificates and apt-transport-https

**Comment by majormoses** [comment]
IMHO If this is a requirement it should be installed, that's what CM does right?

**Comment by smuth4** [comment]
This was actually fixed in #91, I was expecting Github to automagically close this.

**Comment by majormoses** [comment]
@smuth4  it did not close because of the missing "#" before the issue number in commit message.
