### ISSUE TITLE
SSL + uchiwa = json config syntax error

### ISSUE THREAD

**Issue by wezzle** [cmacrae/ansible-sensu#96]
Hi,

When combining `sensu_api_ssl` with `sensu_include_dashboard` there is an syntax error in the generated `uchiwa.json` file. When enabling SSL the jinja template outputs `True` capitalized, which is valid python but not json.

Would you accept a pull-request with the easy fix of adding `| to_nice_json` on the following [line](https://github.com/sensu/sensu-ansible/blob/094060dbdd856bf40e9dfe74d28b6d6dbfaf6e96/templates/uchiwa_config.json.j2#L6)?

Regards,
Wezzle

**Comment by jaredledvina** [comment]
Hey @wezzle,

So sorry for the delay here. I _think_ your PR is solid, a workaround would be to set `sensu_api_ssl: "true"` similar to the default configured here: https://github.com/sensu/sensu-ansible/blob/master/defaults/main.yml#L62. That should make sure that Ansible/Jinja2 treats that variable as a string. I assume you defined `sensu_api_ssl: true` thus, Jinja2 is trying to be helpful and converting it to `True`.
